### ISSUE TITLE
Shadowlands World Map

### ISSUE THREAD

**Issue by ghost** [keyboardturner/WoWMapUprez#1]
**Shadowlands - World Map**

**Screenshots**
https://i.imgur.com/NeKJlbl.jpg

**Additional context**
The world map still has the old BLP images. Can you please fix? Also, I saw some LQ maps on shadowlands beta, would you kindly re-scale these maps too? Thank you for your attention.

**Comment by keyboardturner** [comment]
hi I'll fix this shortly, thanks for reminding me. I meant to push this earlier.
Are there any other maps in particular? I found Oribos and Exile's Reach. I try not to do any dungeons or raids, I'm thinking of doing a specific pack for that later because there are a lot of "microdungeons"

**Comment by keyboardturner** [comment]
I managed to uprez the following zones:

Exile's Reach
"North Sea" (Ocean at Exile's Reach)
Oribos
Updated Cosmic Map

Thank you for the report! Let me know if there's any others - I'm thinking I might add the Covenant halls in a later update as well when I get them organised.
