### ISSUE TITLE
Hellfire Peninsula

### ISSUE THREAD

**Issue by Resike** [keyboardturner/WoWMapUprez#2]
**Zone Name**
Hellfire Peninsula

**Screenshots**
Add screenshots to the specific zone you see the issue.
![image](https://user-images.githubusercontent.com/3955703/103488472-09bf3780-4e0d-11eb-9092-8e482e2899dc.png)

**Additional context**
Top clipping could be fixed.

**Comment by keyboardturner** [comment]
Hi I've pushed a new update that should fix this up a little bit, including the seams also reported in other zones. The seams are unfortunately also just a cause of the upscaling and how Blizz do their maps, but I can still make an effort to fix them by hand.
