### ISSUE TITLE
Shadowmoon Valley (Draenor)

### ISSUE THREAD

**Issue by Resike** [keyboardturner/WoWMapUprez#3]
**Zone Name**
Shadowmoon Valley (Draenor)

**Screenshots**
Add screenshots to the specific zone you see the issue.
![image](https://user-images.githubusercontent.com/3955703/103489479-0cbe2600-4e15-11eb-99f2-4efefc72f737.png)

**Additional context**
Panel misalignments.

**Comment by keyboardturner** [comment]
Bundled in new fix mentioned in [other issue](https://github.com/keyboardturner/WoWMapUprez/issues/2).
