### ISSUE TITLE
Frostfire Ridge

### ISSUE THREAD

**Issue by Resike** [keyboardturner/WoWMapUprez#4]
**Zone Name**
Exact zone name and possible phasing, [e.g. Zul'Drak]. Keep in mind only [these zones](https://github.com/keyboardturner/WoWMapUprez#contents) are currently supported. Raids, dungeons, and microdungeons (caves) are not planned for this release.Frostfire Ridge

**Screenshots**
Add screenshots to the specific zone you see the issue.
![image](https://user-images.githubusercontent.com/3955703/103489493-28293100-4e15-11eb-967a-4a4b6bd8fdd9.png)

**Additional context**
Panel misalignments.

**Comment by keyboardturner** [comment]
Bundled in new fix mentioned in [other issue](https://github.com/keyboardturner/WoWMapUprez/issues/2).
