### ISSUE TITLE
Nagrand (Draenor)

### ISSUE THREAD

**Issue by Resike** [keyboardturner/WoWMapUprez#5]
**Zone Name**
Nagrand (Draenor)

**Screenshots**
![image](https://user-images.githubusercontent.com/3955703/103489528-6d4d6300-4e15-11eb-9b72-d8fa3e9427cc.png)

**Additional context**
Panel misalignments.

**Comment by keyboardturner** [comment]
Bundled in new fix mentioned in [other issue](https://github.com/keyboardturner/WoWMapUprez/issues/2).
