### ISSUE TITLE
Talador

### ISSUE THREAD

**Issue by Resike** [keyboardturner/WoWMapUprez#6]
**Zone Name**
Talador

**Screenshots**
![image](https://user-images.githubusercontent.com/3955703/103489618-2318b180-4e16-11eb-9c44-26c41c1b4448.png)

**Additional context**
Panel misalignments.

**Comment by keyboardturner** [comment]
Bundled in new fix mentioned in [other issue](https://github.com/keyboardturner/WoWMapUprez/issues/2).
