### ISSUE TITLE
Spires of Arak

### ISSUE THREAD

**Issue by Resike** [keyboardturner/WoWMapUprez#7]
**Zone Name**
Spires of Arak

**Screenshots**
Add screenshots to the specific zone you see the issue.
![image](https://user-images.githubusercontent.com/3955703/103489722-ae924280-4e16-11eb-8670-b636c5a61425.png)

**Additional context**
Panel misalignments.

**Comment by keyboardturner** [comment]
Bundled in new fix mentioned in [other issue](https://github.com/keyboardturner/WoWMapUprez/issues/2).
